// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "goa Practice": Application User Types
//
// Command:
// $ goagen
// --design=github.com/imyslx/go-practice/goa/design
// --out=$(GOPATH)/src/github.com/imyslx/go-practice/goa
// --version=v1.3.0

package app
